
<html>
<head>
' PHP PROGRAM TO INPUT DATA AND DISPLAY IT IN ANOTHER  WINDOW 

<title>
data input
</title>
</head>
<body>
<form action="ab.php" method  ="POST">
Roll Number
<input type="text" name="roll"><br><br>
Name 
<input type="text" name="name"><br><br>
Mark 1
<input type="text" name ="mark1"><br><br>
Mark 2
<input type="text" name ="mark2"><br><br>
<input type= "SUBMIT">
</form>

</body>
</html>
