
<html>
<head>

<title>
data input
</title>
<style>.Div1 {
  border: 5px outset red;
  background-color: lightblue;    
  text-align: center;

</style></head>
<body>
<div class="Div1">
<form action="ab1.php" method  ="POST">

Roll Number
<input type="text" name="roll1"  placeholder ="Name"><br><br>
Name 
<input type="text" name="name"><br><br>
Mark 1
<input type="text" name ="mark1"><br><br>
Mark 2
<input type="text" name ="mark2"><br><br>
Mark 3
<input type="text" name ="mark3"><br><br>
Mark 4
<input type="text" name ="mark4"><br><br>
Mark 5
<input type="text" name ="mark5"><br><br>

<input type= "SUBMIT">
</form>
</div>
</body>
</html>
